### ISSUE TITLE
sinks: HTTP sink

### ISSUE THREAD

**Issue by f1shl3gs** [f1shl3gs/vertex#1353]
config might look like this, and `no batch support` , cause our purpose is  triggering something, rather than delivering data.
```yaml
method: POST
headers:
  foo: bar
  content-type: application/json
body: |
  {
    "content": "{{ .message }}"
  }
```
